// user login
const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_PENDING = `${USER_LOGIN}_PENDING`
export const USER_LOGIN_FULFILLED = `${USER_LOGIN}_FULFILLED`
export const USER_LOGIN_REJECTED = `${USER_LOGIN}_REJECTED`

// user signup
const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNUP_PENDING = `${USER_SIGNUP}_PENDING`
export const USER_SIGNUP_FULFILLED = `${USER_SIGNUP}_FULFILLED`
export const USER_SIGNUP_REJECTED = `${USER_SIGNUP}_REJECTED`
//user logout
export const USER_LOGOUT = 'USER_LOGOUT'

export const LOADING_TRUE = 'LOADING_TRUE'
export const LOADING_FALSE = 'LOADING_FALSE'
