// user login
const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_PENDING = `${USER_LOGIN}_PENDING`
export const USER_LOGIN_FULFILLED = `${USER_LOGIN}_FULFILLED`
export const USER_LOGIN_REJECTED = `${USER_LOGIN}_REJECTED`

// user signup
const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNUP_PENDING = `${USER_SIGNUP}_PENDING`
export const USER_SIGNUP_FULFILLED = `${USER_SIGNUP}_FULFILLED`
export const USER_SIGNUP_REJECTED = `${USER_SIGNUP}_REJECTED`
//user logout
export const USER_LOGOUT = 'USER_LOGOUT'

// mentor form
const MENTOR_FORM_SAVE = 'MENTOR_FORM_SAVE'
export const MENTOR_FORM_SAVE_PENDING = `${MENTOR_FORM_SAVE}_PENDING`
export const MENTOR_FORM_SAVE_FULFILLED = `${MENTOR_FORM_SAVE}_FULFILLED`
export const MENTOR_FORM_SAVE_REJECTED = `${MENTOR_FORM_SAVE}_REJECTED`
export const MENTOR_FORM_VIEW_FULFILLED = `MENTOR_FORM_VIEW_FULFILLED`
export const MENTOR_FORM_RESET = 'MENTOR_FORM_RESET'

//feeds
const GET_MENTORS_LIST = 'GET_MENTORS_LIST'
export const GET_MENTORS_LIST_PENDING = `${GET_MENTORS_LIST}_PENDING`
export const GET_MENTORS_LIST_FULFILLED = `${GET_MENTORS_LIST}_FULFILLED`
export const GET_MENTORS_LIST_REJECTED = `${GET_MENTORS_LIST}_REJECTED`

//details
const GET_MENTOR_DETAILS = 'GET_MENTOR_DETAILS'
export const GET_MENTOR_DETAILS_PENDING = `${GET_MENTOR_DETAILS}_PENDING`
export const GET_MENTOR_DETAILS_FULFILLED = `${GET_MENTOR_DETAILS}_FULFILLED`
export const GET_MENTOR_DETAILS_REJECTED = `${GET_MENTOR_DETAILS}_REJECTED`

export const LOADING_TRUE = 'LOADING_TRUE'
export const LOADING_FALSE = 'LOADING_FALSE'
